### ISSUE TITLE
商品詳細から試着へ商品データを受け渡せるようにする

### ISSUE THREAD

**Issue by drumath2237** [faciop-cojt/faciop#22]
試着するときに、3Dオブジェクトを指定できる何らかの手段が欲しい
pluginから指定とかでもいいけど、できればページ間でやり取りできる何らかのスマートな手段がいい

**Comment by eggplants** [comment]
POSTでTry-onに3ddataのURLパスを渡す？

**Comment by eggplants** [comment]
現在のクエリパラメータのidを受けてAPI`https://immense-brook-99073.herokuapp.com/api/v1/goods/{id}`を叩いて`data.data`を見てもらうと早いかも

**Comment by eggplants** [comment]
![image](https://user-images.githubusercontent.com/42153744/88710055-008cb900-d151-11ea-9341-be2f0516776f.png)

受け渡されたGETパラメータのidでAPI叩いてもらう感じで良さそう？

**Comment by drumath2237** [comment]
done
