### ISSUE TITLE
一定期間たつと3Dモデルデータが消える問題

### ISSUE THREAD

**Issue by drumath2237** [faciop-cojt/faciop#43]
herokuのdynoが切れると、ディレクトリの状態が最後のコミットに戻ってしまうため
ディレクトリに保存したglbファイルが消えてしまう問題に対処する

**Comment by eggplants** [comment]
https://blog.mah-lab.com/2013/05/16/heroku-commons-16/

> Dynoに書き込まれたファイルはアイドル状態、または再起動したときに消えてしまいます。永続化したいファイルはS3などのファイルストレージに保存しておきましょう。画像アップロード機能があるアプリにはありがちな罠。

**Comment by eggplants** [comment]
> Dynoは1時間アクセスがないとアイドル状態になる

**Comment by eggplants** [comment]
> 1時間毎にcurl http://your-app-name.herokuapp.com/

**Comment by drumath2237** [comment]
herokuを連続稼働させるためにcronでリクエストさせるやつはたまに見るね

**Comment by eggplants** [comment]
```bash
while :;do curl -s https://faciop-api.herokuapp.com/api/v1/goods|&>/dev/null;sleep 50m;done 
```

**Comment by drumath2237** [comment]
このコマンドはどこで動かす予定ですか？

**Comment by eggplants** [comment]
自分のサーバ

**Comment by drumath2237** [comment]
了解、たぶん解決できると思う

**Comment by eggplants** [comment]
入稿し直してくだち

**Comment by drumath2237** [comment]
ちょっと待っててください
22時過ぎから作業に入ります

**Comment by eggplants** [comment]
OK

**Comment by eggplants** [comment]
明日の朝までDynoくんが生きてれば、俺の勝ち

**Comment by eggplants** [comment]
かなしい

![image](https://user-images.githubusercontent.com/42153744/88987073-b7cf2e80-d30f-11ea-89f0-d8e48dc345f9.png)

**Comment by eggplants** [comment]
https://miyabi-lab.space/blog/23
30分おきだった…？

>Herokuは、無料プランだと 30 分間誰もアクセスをしないと Sleep 状態になってしまい、次にアクセスする際にレスポンスを返すのが遅くなってしまいます。
>10分おき、1時間おき、1日おきから定期的に処理を行わせることが選択できるので、10分おきを選択して、アクセスを定期的に行うことでこの課題が解決します。

**Comment by eggplants** [comment]
```bash
while :;do
  curl -s https://faciop-api.herokuapp.com/api/v1/goods|&>/dev/null
  date
  sleep 10m
done 

```

**Comment by eggplants** [comment]
DBリセット

**Comment by eggplants** [comment]
```bash
heroku pg:reset -a faciop-api --confirm faciop-api
heroku run rails db:migrate -a faciop-api
heroku run rails db:seed -a faciop-api
```
